apiVersion: apps/v1
kind: Deployment
metadata:
  name: connector
  namespace: fabedge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connector
  template:
    metadata:
      labels:
        app: connector
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/connector
                    operator: Exists
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                  - connector
            topologyKey: kubernetes.io/hostname
      hostNetwork: true
      containers:
        - name: strongswan
          image: fabedge/strongswan
          readinessProbe:
            exec:
              command:
              - /usr/sbin/swanctl
              - --version
            initialDelaySeconds: 15
            periodSeconds: 10
          securityContext:
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]
          volumeMounts:
            - name: var-run
              mountPath: /var/run/
            - name: ipsec-d
              mountPath: /etc/ipsec.d/
              readOnly: true
            - name: ipsec-secrets
              mountPath: /etc/ipsec.secrets
              readOnly: true
        - name: connector
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          image: fabedge/connector
          volumeMounts:
            - name: var-run
              mountPath: /var/run/
            - name: connector-config
              mountPath: /etc/fabedge/
            - name: ipsec-d
              mountPath: /etc/ipsec.d/
              readOnly: true
      volumes:
        - name: var-run
          emptyDir: {}
        - name: connector-config
          configMap:
            name: connector-config
        - name: ipsec-d
          hostPath:
            path: /etc/fabedge/ipsec/
        - name: ipsec-secrets
          hostPath:
            path: /etc/fabedge/ipsec/ipsec.secrets
