apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fabedge-operator
rules:
  - apiGroups:
      - community.fabedge.io
    resources:
      - communities
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
      - pods
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - configmaps/status
      - pods/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - "discovery.k8s.io"
    resources:
      - endpointslices
    verbs:
      - get
      - list
      - watch
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: fabedge-operator
  namespace: fabedge

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fabedge-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fabedge-operator
subjects:
  - kind: ServiceAccount
    name: fabedge-operator
    namespace: fabedge
