name: Build

on:
  push:
    branches:
      - main 
    paths-ignore:
      - 'docs/**'
  pull_request:
      branches:
      - main 
      paths-ignore:
      - 'docs/**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Remove CN proxies
      run: |
        bash build/utils/prebuild_for_github.sh
        
    - name: Build Images
      run: |
        make connector-image
        make operator-image
        make agent-image
        make strongswan-image

    - name: Push Images
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker push fabedge/connector 
        docker push fabedge/operator
        docker push fabedge/agent
        docker push fabedge/strongswan
      if: ${{ github.ref == 'refs/heads/main' || contains(github.ref, 'release') }}
