name: Build

on:
  pull_request:
    branches:
      - main 
    paths-ignore:
      - 'docs/**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Remove proxies
      run: |
        bash build/utils/no_proxy.sh
        
    - name: Build
      run: |
        make all